apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yuyaolui/argocd.git
    targetRevision: HEAD
    path: services/blue-green-app
    directory:
      # Set it false as I am using kustomize which will list the desired manifests
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: blue-green-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
